package de.jonasbroeckmann.ksignal

@Suppress("PropertyName", "VariableNaming")
public actual abstract class Signals {
    public actual val ABRT: Signal = Signal("SIGABRT", platform.posix.SIGABRT)
    public actual val ALRM: Signal = Signal("SIGALRM", platform.posix.SIGALRM)
    public actual val BUS: Signal = Signal("SIGBUS", platform.posix.SIGBUS)
    public actual val CLD: Signal = Signal("SIGCLD", platform.posix.SIGCLD)
    public actual val CHLD: Signal = Signal("SIGCHLD", platform.posix.SIGCHLD)
    public actual val CONT: Signal = Signal("SIGCONT", platform.posix.SIGCONT)
    public actual val FPE: Signal = Signal("SIGFPE", platform.posix.SIGFPE)
    public actual val HUP: Signal = Signal("SIGHUP", platform.posix.SIGHUP)
    public actual val ILL: Signal = Signal("SIGILL", platform.posix.SIGILL)
    public actual val INT: Signal = Signal("SIGINT", platform.posix.SIGINT)
    public actual val IO: Signal = Signal("SIGIO", platform.posix.SIGIO)
    public actual val IOT: Signal = Signal("SIGIOT", platform.posix.SIGIOT)
    public actual val KILL: Signal = Signal("SIGKILL", platform.posix.SIGKILL)
    public actual val PIPE: Signal = Signal("SIGPIPE", platform.posix.SIGPIPE)
    public actual val POLL: Signal = Signal("SIGPOLL", platform.posix.SIGPOLL)
    public actual val PROF: Signal = Signal("SIGPROF", platform.posix.SIGPROF)
    public actual val PWR: Signal = Signal("SIGPWR", platform.posix.SIGPWR)
    public actual val QUIT: Signal = Signal("SIGQUIT", platform.posix.SIGQUIT)
    public actual val SEGV: Signal = Signal("SIGSEGV", platform.posix.SIGSEGV)
    public actual val STKFLT: Signal = Signal("SIGSTKFLT", platform.posix.SIGSTKFLT)
    public actual val STOP: Signal = Signal("SIGSTOP", platform.posix.SIGSTOP)
    public actual val SYS: Signal = Signal("SIGSYS", platform.posix.SIGSYS)
    public actual val TERM: Signal = Signal("SIGTERM", platform.posix.SIGTERM)
    public actual val TRAP: Signal = Signal("SIGTRAP", platform.posix.SIGTRAP)
    public actual val TSTP: Signal = Signal("SIGTSTP", platform.posix.SIGTSTP)
    public actual val TTIN: Signal = Signal("SIGTTIN", platform.posix.SIGTTIN)
    public actual val TTOU: Signal = Signal("SIGTTOU", platform.posix.SIGTTOU)
    public actual val UNUSED: Signal = Signal("SIGUNUSED", platform.posix.SIGUNUSED)
    public actual val URG: Signal = Signal("SIGURG", platform.posix.SIGURG)
    public actual val USR1: Signal = Signal("SIGUSR1", platform.posix.SIGUSR1)
    public actual val USR2: Signal = Signal("SIGUSR2", platform.posix.SIGUSR2)
    public actual val VTALRM: Signal = Signal("SIGVTALRM", platform.posix.SIGVTALRM)
    public actual val WINCH: Signal = Signal("SIGWINCH", platform.posix.SIGWINCH)
    public actual val XCPU: Signal = Signal("SIGXCPU", platform.posix.SIGXCPU)
    public actual val XFSZ: Signal = Signal("SIGXFSZ", platform.posix.SIGXFSZ)

    internal actual val Known = listOf(
        ABRT, ALRM, BUS, CLD, CHLD, CONT, FPE, HUP, ILL, INT, IO, IOT, KILL, PIPE, POLL, PROF, PWR, QUIT, SEGV,
        STKFLT, STOP, SYS, TERM, TRAP, TSTP, TTIN, TTOU, UNUSED, URG, USR1, USR2, VTALRM, WINCH, XCPU, XFSZ
    )
}
